Code/WebPhuKien/WebPhuKien/Controllers/PhuKienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPhuKien.Models;
using PagedList;
using PagedList.Mvc;


namespace WebPhuKien.Controllers
{
    public class PhuKienController : Controller
    {
        //
        // GET: /PhuKien/
        DataClasses1DataContext data = new DataClasses1DataContext();
        bool KiemTraStringCoSo(string text) //Kt CHuỗi
        {
            foreach (char c in text)
            {
                if (((c >= '0' && c <= '9')))
                {
                    return true;
                }
            }
            return false;
        }
        bool KiemTraStringLaSo(string text) //Kt CHuỗi
        {
            foreach (char c in text)
            {
                if (((c >= '0' && c <= '9')))
                {

                }
                else
                    return false;
            }
            return true;
        }

        private List<SANPHAM> Laysanpham(int count)
        {
            return data.SANPHAMs.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }

        public ActionResult Index(int ? page)
        {
          //  var spmoi = Laysanpham(3);
          //  return View(spmoi);
            int pageSize = 3;
            int pageNum = (page ?? 1);

            var spmoi = Laysanpham(9);
            return View(spmoi.ToPagedList(pageNum, pageSize));

        }
        public ActionResult LoaiSP()
        {

            return PartialView(data.LOAISANPHAMs.Select(a => a).OrderBy(a=>a.Tenloai));
        }

        public ActionResult NhaSX()
        {
            return PartialView(data.NHASANXUATs.Select(a => a).OrderBy(a=>a.Tennsx));
        }
        public ActionResult ChiTiet(string id)
        {
           
            var sp = data.SANPHAMs.Where(a => a.Idsp == id);
            return View(sp.Single());
        }
        public ActionResult SPTheoLoai(string id, int? page)
        {
            int pageSize = 9;
            int pageNum = (page ?? 1);
            var sach = data.SANPHAMs.Where(a => a.Idloai == id);
            return View(sach.ToPagedList(pageNum,pageSize));
        }
        public ActionResult SPTheoNSX(string id, int? page)
        {

            int pageSize = 9;
            int pageNum = (page ?? 1);
            var sach = data.SANPHAMs.Where(a => a.Idnsx == id);
            return View(sach.ToPagedList(pageNum,pageSize));
        }
        public ActionResult ThongTinShop()
        {
            var thongtin = data.THONGTINs.Select(n=>n).First();
            return View(thongtin);
        }
        [HttpGet]
        public ActionResult LienHe()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LienHe(FormCollection collection,LIENHE LH)
        {
            string user = collection["Hoten"];            
            string Email = collection["Email"];
            string SDT = collection["Sdt"];
            string Tittle = collection["Tieude"];
            string Content = collection["Noidung"];
            Boolean coloi = false;
            if (String.IsNullOrEmpty(user)||user.Length>25||KiemTraStringCoSo(user))
            {
                ViewData["Loi1"] = "Nhập Tên Tối Đa 25 Ký Tự !";
                coloi = true;
            }
            if (String.IsNullOrEmpty(Email)||Email.Length>50)
            {
                ViewData["Loi2"] = "Nhập Email Tối Đa 50 Ký Tự !";
                coloi = true;
            }
            
            if (!String.IsNullOrEmpty(SDT)&&(SDT.Length>11||SDT.Length<10||!KiemTraStringLaSo(SDT)))
            {
                ViewData["Loi3"] = "Sai Số Điện Thoại ! ";
                coloi = true;
            }
            if (String.IsNullOrEmpty(Tittle)||Tittle.Length>150)
            {
                ViewData["Loi4"] = "Nhập tiêu đề tối đa 150 ký tự !";
                coloi = true;
            }
            if (String.IsNullOrEmpty(Content)||Content.Length>500)
            {
                ViewData["Loi5"] = "Nhập nội dung cần gửi ! Tối đa 500 ký tự ( Bao Gồm Các Thẻ Định Dạng HTML )";
                coloi = true;
            }
            if (coloi)
            {

                return this.LienHe();
            }
                LH.HOTEN = user;
                LH.EMAIL = Email;
                LH.TIEUDE = Tittle;
                LH.NOIDUNG = Content;
                LH.SDT = SDT;
                data.LIENHEs.InsertOnSubmit(LH);
                data.SubmitChanges();
                return RedirectToAction("Sent");

        }
        public ActionResult Sent()
        {
            return View();
        }
	}
}

Code/WebPhuKien/WebPhuKien/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Code/WebPhuKien/WebPhuKien/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Trang Quản Lý</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/content/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/content/shop-homepage.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
</head>
<body>
  
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Admin")">Trang chính</a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("EditTTShop", "Admin")">Thông Tin Shop</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Banner", "Admin")">Banner Quảng Cáo</a></li>
                    <li>
                        <a href="@Url.Action("Phanhoi","Admin")">Mục phản hồi</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="@Url.Action("Changepass","Admin")">Đổi Mật Khẩu</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">
                <div> @RenderBody() </div>
        </div>
    <!-- /.container -->
    <div class="container">
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Myanimeshop</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->
    <!-- jQuery -->
    <script src="~/Scripts/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Code/WebPhuKien/WebPhuKien/Views/Shared/_LayoutPageUser.cshtml
<!DOCTYPE html>

<html xmlns:fb ='http://www.facebook.com/2008/fbml'>
    <head>
        <meta property="fb:app_id" content="1230330800319049" />
        <meta property="fb:admins" content="100000686899395" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Trang bán hàng phụ kiện Anime/Manga ~ Du hành vào thế giới 2D</title>
        <!-- Bootstrap Core CSS -->
        <link href="~/content/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="~/content/shop-homepage.css" rel="stylesheet">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div id="fb-root"></div>
        <script>
            (function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7&appId=1230330800319049";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>
              <!-- Navigation -->
                <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="@Url.Action("Index","Phukien")">Trang chủ</a>

                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li>
                                    <a href="@Url.Action("ThongTinShop","PhuKien")">Thông tin shop</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("LienHe","PhuKien")">Liên hệ</a>
                                </li>
                                <li>
                                    @Html.Action("GiohangPartial", "Giohang")
                                </li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                    @Html.Action("Hientenuser", "Nguoidung")
                            </ul>
                        </div>
                        <!-- /.navbar-collapse -->
                    </div>
                    <!-- /.container -->
                </nav>
                <!-- Page Content -->
                <div class="container">
                    <div class="row">

                        <div class="col-md-3">
                @Html.Action("LoaiSP", "PhuKien")
                @Html.Action("NhaSX", "PhuKien")
                        </div>
                        <div class="col-md-9">

                            <div class="row carousel-holder"> @Html.Action("Index", "Banner")</div>
                            <div> @RenderBody() </div>
                        </div>
                    </div>
                </div>
                <!-- /.container -->
                <div class="container">
                    <hr>
                    <!-- Footer -->
                    <footer>
                        <div class="row">
                            <div class="col-lg-12">
                                <p>Copyright &copy; Myanimeshop.com</p>
                            </div>
                        </div>
                    </footer>
                </div>
                <!-- /.container -->
                <!-- jQuery -->
                <script src="~/Scripts/jquery.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="~/Scripts/bootstrap.min.js"></script>
    </body>
    </html>

Code/WebPhuKien/WebPhuKien/Views/Shared/_LayoutPageUserNoBanner.cshtml
<!DOCTYPE html>

<html xmlns:fb='http://www.facebook.com/2008/fbml'>
<head>

    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Trang bán hàng phụ kiện Anime/Manga ~ Du hành vào thế giới 2D</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/content/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/content/shop-homepage.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '938285796282295',
                xfbml: true,
                version: 'v2.7'
            });
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) { return; }
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Phukien")">Trang chủ</a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("ThongTinShop","PhuKien")">Thông tin shop</a>
                    </li>
                    <li>
                        <a href="#">Tất cả sản phẩm</a>
                    </li>
                    <li>
                        <a href="@Url.Action("LienHe","PhuKien")">Liên hệ</a>
                    </li>
                    <li>
                        @Html.Action("GiohangPartial", "Giohang")
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @Html.Action("Hientenuser", "Nguoidung")
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">
        <div class="row">

            <div class="col-md-3">
                @Html.Action("LoaiSP", "PhuKien")
                @Html.Action("NhaSX", "PhuKien")
            </div>
            <div class="col-md-9">
                <div> @RenderBody() </div>
            </div>
        </div>
    </div>
    <!-- /.container -->
    <div class="container">
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Yoloshop.com</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->
    <!-- jQuery -->
    <script src="~/Scripts/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Code/WebPhuKien/WebPhuKien/Views/Shared/_LayoutUserPageNoBanner.cshtml
<!DOCTYPE html>

<html xmlns:fb='http://www.facebook.com/2008/fbml'>
<head>
    <meta property="fb:app_id" content="1230330800319049" />
    <meta property="fb:admins" content="100000686899395" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Trang bán hàng phụ kiện Anime/Manga ~ Du hành vào thế giới 2D</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/content/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/content/shop-homepage.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    

</head>
<body>
    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7&appId=1230330800319049";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>



    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Phukien")">Trang chủ</a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("ThongTinShop","PhuKien")">Thông tin shop</a>
                    </li>
                    <li>
                        <a href="@Url.Action("LienHe","PhuKien")">Liên hệ</a>
                    </li>
                    <li>
                        @Html.Action("GiohangPartial", "Giohang")
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @Html.Action("Hientenuser", "Nguoidung")
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">
        <div class="row">

            <div class="col-md-3">
                @Html.Action("LoaiSP", "PhuKien")
                @Html.Action("NhaSX", "PhuKien")
            </div>
            <div class="col-md-9">
                <div> @RenderBody() </div>
            </div>
        </div>
    </div>
    <!-- /.container -->
    <div class="container">
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Myanimeshop.com</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->
    <!-- jQuery -->
    <script src="~/Scripts/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>